@url = "http://localhost:3000/"

GET http://localhost:3000/flight HTTP/1.1
###
POST http://localhost:3000/flight HTTP/1.1
Content-Type: application/json

{
    "title": "flight to Niger",
    "time": "1pm",
    "price": "26000",
    "date": "26-06-2022"
}
###
GET http://localhost:3000/flight/aa071b55-4513-4714-a38b-44c8aaecc61c HTTP/1.1
###
PUT http://localhost:3000/flight/aa071b55-4513-4714-a38b-44c8aaecc61c HTTP/1.1
Content-Type: application/json

{
    "title": "flight to Ghana",
    "time": "1pm",
    "price": "26000",
    "date": "26-06-2022"
}
